version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/bootstrap"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/impress.js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/typed.js"
    schedule:
      interval: "weekly"
